#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->register(\Horat1us\Deploy\Console\Commands\InitCommand::class);

$application->run();